environment:
  nodejs_version: "18"

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - yarn install --non-interactive   # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint  # скрипт тестирования
